apiVersion: v1
kind: Namespace
metadata:
  name: proxy
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: proxy
  namespace: proxy
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.ds.image }}
        name: iptables
        securityContext:
          privileged: true
        env:
        - name: "http_proxy"
          value: {{ .Values.global.httpProxy }}
        - name: "https_proxy"
          value: {{ .Values.global.httpsProxy }}
      hostNetwork: true
